entity.config_readonly_filter.collection:
  path: '/admin/config/system/config_readonly_filter'
  defaults:
    _entity_list: 'config_readonly_filter'
    _title: 'Config read-only filters'
  requirements:
    _permission: 'administer configuration read-only filter'
  options:
    _admin_route: TRUE

entity.config_readonly_filter.delete_form:
  path: '/admin/config/system/config_readonly_filter/manage/{config_readonly_filter}/delete'
  defaults:
    _entity_form: 'config_readonly_filter.delete'
    _title: 'Delete'
  requirements:
    _permission: 'administer configuration read-only filter'
  options:
    _admin_route: TRUE

entity.config_readonly_filter.add_form:
  path: '/admin/config/system/config_readonly_filter/add'
  defaults:
    _entity_form: 'config_readonly_filter.add'
    _title: 'Add config read-only filter'
  requirements:
    _permission: 'administer configuration read-only filter'
  options:
    _admin_route: TRUE

entity.config_readonly_filter.edit_form:
  path: '/admin/config/system/config_readonly_filter/manage/{config_readonly_filter}'
  defaults:
    _entity_form: 'config_readonly_filter.edit'
    _title: 'Edit'
  requirements:
    _permission: 'administer configuration read-only filter'
  options:
    _admin_route: TRUE
